import { useCallback, useEffect, useMemo, useState } from 'react'
import { ArrowRight, CalendarDays, ChevronDown, Heart, Plus, Sparkles, Star } from 'lucide-react'
import { AddMemoryLauncher, AppShell, AnniversaryHero, AvatarStack, CalendarCell, CalendarPanel, EmptyState, FilterChip, MemoryBadge, MemoryCard, MemoryDetail, MonthSwitcher, PageHeader, PhotoStack, SearchField, SectionHeader, SkeletonCard, TypeIcon } from './components/tandem/components'
import { formatMemoryDate, getAnniversaryCopy, groupMemoriesByYear, memoryTypeLabels } from './data/tandemData'
import { ApiError, tandemApi } from './lib/tandemApi'
import { validateMemoryDraft } from './lib/memoryValidation'

const PLACEHOLDER_IMAGE = 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="800" height="500" viewBox="0 0 800 500"%3E%3Crect width="800" height="500" fill="%23eee4dc"/%3E%3Cpath d="M0 400c130-90 240-30 350-90s230-100 450 30v160H0Z" fill="%23dfc9bd"/%3E%3Ccircle cx="630" cy="130" r="62" fill="%23f6eee7"/%3E%3C/svg%3E'

function toMemory(apiMemory, members) {
  const metadata = apiMemory.metadata || {}
  const location = metadata.formatted_address || metadata.name || metadata.destination || ''
  const excerpt = apiMemory.notes || metadata.activity_kind || metadata.label || 'A memory worth keeping close.'
  return {
    id: apiMemory.id, tandemId: apiMemory.tandem_id, title: apiMemory.title, type: apiMemory.category, date: apiMemory.local_date,
    location, participants: apiMemory.participants.map((participant) => participant.display_name), participantIds: apiMemory.participants.map((participant) => participant.user_id), excerpt,
    notes: apiMemory.notes || undefined, rating: apiMemory.rating || undefined, tags: apiMemory.tags, image: PLACEHOLDER_IMAGE, imageAlt: 'A place reserved for a future memory photo', source: metadata.provider,
    version: apiMemory.version, metadata, createdBy: apiMemory.created_by, createdByName: members.find((member) => member.user_id === apiMemory.created_by)?.display_name,
  }
}

function TodayScreen({ memories, onOpen, onAddMemory, onNavigate }) {
  const recent = memories.slice().sort((a, b) => b.date.localeCompare(a.date)).slice(0, 3)
  return <div className="screen today-screen"><PageHeader eyebrow="Your shared archive" title="Your shared story, lately." description="A little place for the days you want to keep close." action={<button className="button button-quiet" onClick={() => onNavigate('/calendar')}><CalendarDays size={16} /> View calendar</button>} /><AnniversaryHero memory={undefined} copy={getAnniversaryCopy()} onOpen={onOpen} onAddMemory={onAddMemory} /><div className="today-lower-grid"><section><SectionHeader eyebrow="Keep adding to it" title="Recently added" action="See timeline" onAction={() => onNavigate('/timeline')} />{recent.length ? <div className="memory-grid memory-grid-three">{recent.map((memory) => <MemoryCard key={memory.id} memory={memory} onOpen={onOpen} />)}</div> : <EmptyState title="The first page is waiting." description="Add a memory and your shared story will start taking shape." action="Add a memory" onAction={onAddMemory} />}</section><aside className="shuffle-card"><div className="shuffle-heading"><span className="eyebrow">A little nudge</span><span className="shuffle-icon"><Sparkles size={17} /></span></div><PhotoStack memories={recent} onOpen={onOpen} /><div className="shuffle-copy"><h3>Something worth remembering</h3><p>Every memory starts as a small detail worth keeping.</p></div>{recent[0] ? <button className="button button-secondary button-full" onClick={() => onOpen(recent[0].id)}>Open a memory <ArrowRight size={15} /></button> : <button className="button button-secondary button-full" onClick={onAddMemory}>Make the first one <Plus size={15} /></button>}</aside></div></div>
}

function TimelineScreen({ memories, onOpen, onAddMemory }) {
  const [activeType, setActiveType] = useState('all'); const [sort, setSort] = useState('newest')
  const filtered = memories.filter((memory) => activeType === 'all' || memory.type === activeType); const ordered = sort === 'newest' ? filtered : filtered.slice().reverse(); const grouped = groupMemoriesByYear(ordered)
  return <div className="screen timeline-screen"><PageHeader eyebrow="The story so far" title="Our timeline" description="A chronological record of the places, rituals, and little milestones that became ours." action={<button className="button button-primary" onClick={onAddMemory}><Plus size={16} /> Add memory</button>} /><div className="timeline-toolbar"><div className="filter-row" aria-label="Filter memories by type"><FilterChip active={activeType === 'all'} onClick={() => setActiveType('all')}>Everything</FilterChip>{['movie', 'place', 'trip', 'activity', 'custom'].map((type) => <FilterChip key={type} active={activeType === type} onClick={() => setActiveType(type)} icon={<TypeIcon type={type} />}>{memoryTypeLabels[type]}</FilterChip>)}</div><label className="select-wrap"><span className="sr-only">Sort timeline</span><select value={sort} onChange={(event) => setSort(event.target.value)}><option value="newest">Newest first</option><option value="oldest">Oldest first</option></select><ChevronDown size={15} /></label></div>{grouped.length === 0 ? <EmptyState title="The next chapter is waiting." description="Nothing matches this filter yet. Add a new memory to begin." action="Add a memory" onAction={onAddMemory} /> : <div className="timeline-groups">{grouped.map((group) => <section className="timeline-year" key={group.year}><div className="timeline-year-label"><span>{group.year}</span><span className="year-rule" /></div><div className="timeline-months">{group.months.map((month) => <div className="timeline-month" key={month.label}><h2>{month.label}</h2><div className="timeline-items">{month.memories.map((memory) => <TimelineMemory key={memory.id} memory={memory} onOpen={onOpen} />)}</div></div>)}</div></section>)}</div>}</div>
}

function TimelineMemory({ memory, onOpen }) {
  const date = new Date(`${memory.date}T12:00:00`)
  return <article className="timeline-memory"><div className="timeline-date"><strong>{String(date.getDate()).padStart(2, '0')}</strong><span>{date.toLocaleDateString('en-US', { weekday: 'short' })}</span></div><div className="timeline-line" /><button className="timeline-memory-card" onClick={() => onOpen(memory.id)}><img src={memory.image} alt={memory.imageAlt} /><div className="timeline-memory-copy"><div className="memory-card-meta"><span>{formatMemoryDate(memory.date)}</span>{memory.location && <><span className="meta-separator">·</span><span>{memory.location}</span></>}</div><h3>{memory.title}</h3><p>{memory.excerpt}</p><div className="timeline-memory-bottom"><MemoryBadge type={memory.type} /><span>{memory.participants.join(' & ')}</span>{memory.rating && <span className="rating"><Star size={12} fill="currentColor" />{memory.rating}/10</span>}</div></div><span className="timeline-open"><ArrowRight size={17} /></span></button></article>
}

function ExploreScreen({ memories, onOpen, query, onQueryChange, activeType, setActiveType, activeYear, setActiveYear }) {
  const years = [...new Set(memories.map((memory) => memory.date.slice(0, 4)))].sort().reverse()
  return <div className="screen explore-screen"><PageHeader eyebrow="Find it again" title="Explore your memories" description="Search the small details you might otherwise forget." /><SearchField value={query} onChange={onQueryChange} /><div className="explore-filter-line"><div className="filter-row"><FilterChip active={activeType === 'all'} onClick={() => setActiveType('all')}>All memories</FilterChip>{['movie', 'place', 'trip', 'activity', 'custom'].map((type) => <FilterChip key={type} active={activeType === type} onClick={() => setActiveType(type)} icon={<TypeIcon type={type} />}>{memoryTypeLabels[type]}</FilterChip>)}</div><div className="filter-selects"><label className="small-select"><span>Year</span><select value={activeYear} onChange={(event) => setActiveYear(event.target.value)}><option value="all">Any year</option>{years.map((year) => <option key={year}>{year}</option>)}</select><ChevronDown size={14} /></label></div></div><section className="explore-results"><SectionHeader eyebrow={`${memories.length} memories`} title={query ? `Results for “${query}”` : 'All the good stuff'} /><div className="memory-grid memory-grid-three">{memories.map((memory) => <MemoryCard key={memory.id} memory={memory} onOpen={onOpen} />)}</div>{memories.length === 0 && <EmptyState title="That memory is playing hide and seek." description="Try a different word, year, or filter." action="Clear filters" onAction={() => { onQueryChange(''); setActiveType('all'); setActiveYear('all') }} />}</section></div>
}

function CalendarScreen({ memories, onOpen, onAddMemory }) {
  const today = new Date(); const [month, setMonth] = useState(new Date(today.getFullYear(), today.getMonth(), 1)); const [selectedDate, setSelectedDate] = useState(memories[0]?.date || today.toISOString().slice(0, 10)); const year = month.getFullYear(); const monthIndex = month.getMonth(); const daysInMonth = new Date(year, monthIndex + 1, 0).getDate(); const firstDay = new Date(year, monthIndex, 1).getDay(); const selectedMemory = memories.find((memory) => memory.date === selectedDate); const monthLabel = month.toLocaleDateString('en-US', { month: 'long', year: 'numeric' }); const shiftMonth = (amount) => setMonth(new Date(year, monthIndex + amount, 1))
  return <div className="screen calendar-screen"><PageHeader eyebrow="A year at a glance" title="Calendar" description="The dates are part of the story, too." action={<button className="button button-primary" onClick={onAddMemory}><Plus size={16} /> Add memory</button>} /><div className="calendar-layout"><section className="calendar-main"><div className="calendar-heading"><MonthSwitcher label={monthLabel} onPrevious={() => shiftMonth(-1)} onNext={() => shiftMonth(1)} /><div className="calendar-legend"><span><i className="legend-image" />Memory</span><span><i className="legend-today" />Today</span></div></div><div className="calendar-weekdays">{['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].map((day) => <span key={day}>{day}</span>)}</div><div className="calendar-grid">{Array.from({ length: firstDay }).map((_, index) => <div className="calendar-cell calendar-cell-blank" key={`blank-${index}`} />)}{Array.from({ length: daysInMonth }, (_, index) => index + 1).map((day) => { const date = `${year}-${String(monthIndex + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`; const memory = memories.find((item) => item.date === date); return <CalendarCell key={date} day={day} memory={memory} selected={selectedDate === date} onSelect={() => setSelectedDate(date)} /> })}</div></section><aside className="calendar-sidebar"><div className="calendar-side-heading"><div><div className="eyebrow">Selected day</div><h2>{selectedMemory ? 'A day to keep' : 'A quiet day'}</h2></div></div><CalendarPanel memory={selectedMemory} onOpen={onOpen} /></aside></div></div>
}

function TandemScreen({ tandem, members, memories, onAddMemory }) {
  const displayMembers = members.map((member, index) => ({ id: member.user_id, name: member.display_name, initials: member.display_name.slice(0, 2).toUpperCase(), color: index ? '#b86d57' : '#8f4357' }))
  return <div className="screen tandem-screen"><div className="tandem-intro"><div><div className="eyebrow">The people in the story</div><h1>Our tandem</h1><p>A private space for the people who make the memories matter.</p></div><button className="button button-primary" onClick={onAddMemory}><Plus size={16} /> Add memory</button></div><section className="tandem-identity-card"><div className="tandem-identity-art"><div className="identity-orbit orbit-one" /><div className="identity-orbit orbit-two" /><AvatarStack members={displayMembers} size="large" /><span className="identity-sparkle sparkle-one">✦</span><span className="identity-sparkle sparkle-two">✧</span></div><div className="tandem-identity-copy"><span className="eyebrow">Your shared archive</span><h2>{tandem.name}</h2><p>Every memory here belongs to the members of this private tandem.</p><div className="tandem-stats"><div><strong>{memories.length}</strong><span>memories</span></div><div><strong>{members.length}</strong><span>members</span></div><div><strong>{new Date(tandem.created_at).getFullYear()}</strong><span>started</span></div></div></div></section><div className="tandem-columns"><section className="tandem-panel"><SectionHeader eyebrow="The people here" title="Members" /><div className="member-list">{members.map((member) => <div className="member-row" key={member.user_id}><span className="member-avatar" style={{ backgroundColor: '#8f4357' }}>{member.display_name.slice(0, 2).toUpperCase()}</span><span><strong>{member.display_name}</strong><small>{member.role}</small></span><span className="member-status">Active</span></div>)}</div></section><section className="tandem-panel invite-panel"><div className="invite-icon"><Heart size={19} /></div><div><div className="eyebrow">Keep it close</div><h2>Private by default</h2><p>Your memories are only visible to members of this tandem.</p></div></section></div></div>
}

function MemoryForm({ category, memory, members, tandemId, timezone, onCancel, onSaved }) {
  const [form, setForm] = useState(() => ({ category: memory?.type || category, title: memory?.title || '', local_date: memory?.date || new Date().toISOString().slice(0, 10), timezone: timezone, notes: memory?.notes || '', rating: memory?.rating || '', tags: memory?.tags.join(', ') || '', participant_ids: memory?.participantIds || [], metadata: memory?.metadata || {} })); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const set = (key, value) => setForm((current) => ({ ...current, [key]: value })); const setMetadata = (key, value) => setForm((current) => ({ ...current, metadata: { ...current.metadata, [key]: value } })); const metadata = form.metadata
  const submit = async (event) => { event.preventDefault(); setError(''); const tags = form.tags.split(',').map((tag) => tag.trim()).filter(Boolean); const clientErrors = validateMemoryDraft({ title: form.title, timezone: form.timezone, rating: form.rating, tags }); if (clientErrors.length) { setError(clientErrors.join(' ')); return } setSaving(true); const input = { category: form.category, title: form.title, local_date: form.local_date, timezone: form.timezone, notes: form.notes || null, rating: form.rating ? Number(form.rating) : null, participant_ids: form.participant_ids, tags, metadata }; try { const saved = memory ? await tandemApi.updateMemory(tandemId, memory.id, { ...input, expected_version: memory.version }) : await tandemApi.createMemory(tandemId, input); onSaved(saved) } catch (caught) { const apiError = caught instanceof ApiError ? caught : null; if (apiError?.status === 409) setError(`This memory changed while you were editing it. Reload it before saving again${apiError.detail?.current_version ? ` (current version ${apiError.detail.current_version})` : ''}.`); else if (apiError?.status === 422) setError(typeof apiError.detail === 'string' ? apiError.detail : 'Please check the details and try again.'); else setError(apiError?.message || 'We could not save this memory. Try again.') } finally { setSaving(false) } }
  const categoryFields = form.category === 'trip' ? <div className="form-grid"><label>Destination<input value={metadata.destination || ''} onChange={(event) => setMetadata('destination', event.target.value)} maxLength="180" /></label><label>Trip end date<input type="date" value={metadata.end_date || ''} onChange={(event) => setMetadata('end_date', event.target.value || undefined)} /></label></div> : form.category === 'place' ? <label>Place name<input value={metadata.name || ''} onChange={(event) => setMetadata('name', event.target.value)} maxLength="180" /><small>Manual place details are supported; enrichment arrives in the next milestone.</small></label> : form.category === 'movie' ? <div className="form-grid"><label>Release year<input type="number" value={metadata.release_year || ''} onChange={(event) => setMetadata('release_year', event.target.value ? Number(event.target.value) : undefined)} min="1888" max="2200" /></label><label>Movie title snapshot<input value={metadata.movie_title_snapshot || ''} onChange={(event) => setMetadata('movie_title_snapshot', event.target.value)} maxLength="180" /></label></div> : form.category === 'activity' ? <label>Activity kind<input value={metadata.activity_kind || ''} onChange={(event) => setMetadata('activity_kind', event.target.value)} maxLength="120" placeholder="Dinner, hike, concert…" /></label> : null
  return <div className="form-backdrop"><section className="memory-form" role="dialog" aria-modal="true" aria-labelledby="memory-form-title"><div className="form-heading"><div><div className="eyebrow">{memory ? 'Shape it a little differently' : 'Make a little room for it'}</div><h2 id="memory-form-title">{memory ? 'Edit memory' : `Add a ${memoryTypeLabels[form.category].toLowerCase()}`}</h2></div><button className="icon-button" onClick={onCancel} aria-label="Close memory form">×</button></div><form onSubmit={submit}><div className="form-grid"><label>Title<input autoFocus required value={form.title} onChange={(event) => set('title', event.target.value)} maxLength="180" placeholder="Give this memory a name" /></label><label>Type<select value={form.category} disabled={Boolean(memory)} onChange={(event) => set('category', event.target.value)}>{Object.entries(memoryTypeLabels).filter(([key]) => key !== 'moment').map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label></div>{categoryFields}<div className="form-grid"><label>Date<input type="date" required value={form.local_date} onChange={(event) => set('local_date', event.target.value)} /></label><label>Timezone<input required value={form.timezone} onChange={(event) => set('timezone', event.target.value)} placeholder="America/Chicago" /></label></div><label>Notes<textarea value={form.notes} onChange={(event) => set('notes', event.target.value)} maxLength="10000" rows="4" placeholder="What do you want to remember?" /></label><div className="form-grid"><label>Rating <span className="form-hint">optional, 1–10</span><input type="number" min="1" max="10" value={form.rating} onChange={(event) => set('rating', event.target.value)} /></label><label>Tags <span className="form-hint">comma-separated</span><input value={form.tags} onChange={(event) => set('tags', event.target.value)} placeholder="summer, food" /></label></div><fieldset><legend>Who was there?</legend><div className="member-checks">{members.map((member) => <label key={member.user_id}><input type="checkbox" checked={form.participant_ids.includes(member.user_id)} onChange={(event) => set('participant_ids', event.target.checked ? [...form.participant_ids, member.user_id] : form.participant_ids.filter((id) => id !== member.user_id))} />{member.display_name}</label>)}</div></fieldset>{error && <p className="form-error" role="alert">{error}</p>}<div className="form-actions"><button type="button" className="button button-quiet" onClick={onCancel}>Cancel</button><button type="submit" className="button button-primary" disabled={saving}>{saving ? 'Saving…' : memory ? 'Save changes' : 'Add memory'}</button></div></form></section></div>
}

function LoadingScreen() { return <div className="screen loading-screen"><PageHeader eyebrow="Opening your space" title="A moment…" /><div className="memory-grid memory-grid-three"><SkeletonCard /><SkeletonCard /><SkeletonCard /></div></div> }
function ErrorScreen({ message, onRetry }) { return <div className="screen error-screen"><EmptyState title="We couldn’t open this page." description={message || 'Your memories are safe. Try again in a moment.'} action="Try again" onAction={onRetry} /></div> }

export default function App() {
  const [path, setPath] = useState(() => window.location.pathname || '/'); const [user, setUser] = useState(null); const [tandem, setTandem] = useState(null); const [members, setMembers] = useState([]); const [memories, setMemories] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [launcherOpen, setLauncherOpen] = useState(false); const [draftCategory, setDraftCategory] = useState(null); const [editingMemory, setEditingMemory] = useState(null); const [query, setQuery] = useState(() => new URLSearchParams(window.location.search).get('q') || ''); const [exploreType, setExploreType] = useState('all'); const [exploreYear, setExploreYear] = useState('all'); const [notice, setNotice] = useState('')
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [currentUser, tandems] = await Promise.all([tandemApi.me(), tandemApi.tandems()]); setUser(currentUser); const currentTandem = tandems[0]; if (!currentTandem) { setTandem(null); setMembers([]); setMemories([]); return } setTandem(currentTandem); const [currentMembers, result] = await Promise.all([tandemApi.members(currentTandem.id), path.startsWith('/memory/') ? tandemApi.memory(currentTandem.id, path.split('/')[2]).then((item) => ({ items: [item] })) : tandemApi.memories(currentTandem.id, path === '/explore' ? { q: query || undefined, category: exploreType === 'all' ? undefined : exploreType, year: exploreYear === 'all' ? undefined : Number(exploreYear) } : {})]); setMembers(currentMembers); setMemories(result.items.map((item) => toMemory(item, currentMembers))) } catch (caught) { const apiError = caught instanceof ApiError ? caught : null; setError(apiError?.status === 401 ? 'Please sign in to open your private tandem.' : apiError?.message || 'The Tandem service is unavailable.') } finally { setLoading(false) } }, [path, query, exploreType, exploreYear])
  useEffect(() => { load(); const onPopState = () => setPath(window.location.pathname || '/'); window.addEventListener('popstate', onPopState); return () => window.removeEventListener('popstate', onPopState) }, [load])
  useEffect(() => { if (!notice) return undefined; const timeout = window.setTimeout(() => setNotice(''), 3200); return () => window.clearTimeout(timeout) }, [notice])
  const navigate = (nextPath) => { const [pathname, search = ''] = nextPath.split('?'); window.history.pushState({}, '', `${pathname}${search ? `?${search}` : ''}`); setPath(pathname || '/'); if (search) setQuery(new URLSearchParams(search).get('q') || '') }
  const refresh = async (savedMemory) => { setDraftCategory(null); setEditingMemory(null); setLauncherOpen(false); if (savedMemory) navigate(`/memory/${savedMemory.id}`); await load(); setNotice('Memory saved to your tandem.') }
  const deleteMemory = async (memory) => { if (!window.confirm(`Delete “${memory.title}”? This cannot be undone.`)) return; try { await tandemApi.deleteMemory(tandem.id, memory.id, memory.version); navigate('/timeline'); await load(); setNotice('Memory deleted.') } catch (caught) { setNotice(caught instanceof ApiError && caught.status === 409 ? 'That memory changed. Reload it before deleting.' : 'We could not delete that memory.') } }
  const snapshot = useMemo(() => tandem ? { tandem, members, memories } : null, [tandem, members, memories]); const detailId = path.startsWith('/memory/') ? path.split('/')[2] : null; const detailMemory = memories.find((memory) => memory.id === detailId); let screen = null
  if (snapshot) { if (detailId) screen = detailMemory ? <MemoryDetail memory={detailMemory} onBack={() => navigate('/timeline')} onAddMemory={() => setLauncherOpen(true)} onEdit={() => setEditingMemory(detailMemory)} onDelete={() => deleteMemory(detailMemory)} /> : <EmptyState title="Memory not found" description="This memory may have been deleted or is outside this tandem." action="Back to timeline" onAction={() => navigate('/timeline')} />; else if (path === '/timeline') screen = <TimelineScreen memories={memories} onOpen={(id) => navigate(`/memory/${id}`)} onAddMemory={() => setLauncherOpen(true)} />; else if (path === '/explore') screen = <ExploreScreen memories={memories} onOpen={(id) => navigate(`/memory/${id}`)} query={query} onQueryChange={setQuery} activeType={exploreType} setActiveType={setExploreType} activeYear={exploreYear} setActiveYear={setExploreYear} />; else if (path === '/calendar') screen = <CalendarScreen memories={memories} onOpen={(id) => navigate(`/memory/${id}`)} onAddMemory={() => setLauncherOpen(true)} />; else if (path === '/tandem') screen = <TandemScreen tandem={tandem} members={members} memories={memories} onAddMemory={() => setLauncherOpen(true)} />; else screen = <TodayScreen memories={memories} onOpen={(id) => navigate(`/memory/${id}`)} onAddMemory={() => setLauncherOpen(true)} onNavigate={navigate} /> }
  const startAdd = (category) => { setLauncherOpen(false); setDraftCategory(category) }
  return <AppShell path={path} onNavigate={navigate} onAddMemory={() => setLauncherOpen(true)} query={query} onQueryChange={setQuery} tandemName={tandem?.name} currentUserName={user?.display_name}><>{error ? <ErrorScreen message={error} onRetry={load} /> : loading ? <LoadingScreen /> : screen || <EmptyState title="Create your first tandem" description="Tandem is invite-only. Ask an owner to invite this account." />} {notice && <div className="toast-notice" role="status"><Sparkles size={16} /><span>{notice}</span></div>}<AddMemoryLauncher open={launcherOpen} onClose={() => setLauncherOpen(false)} onChoose={startAdd} />{(draftCategory || editingMemory) && tandem && <MemoryForm category={draftCategory || editingMemory.type} memory={editingMemory ? { ...editingMemory, tandemId: tandem.id } : null} members={members} tandemId={tandem.id} timezone={tandem.timezone} onCancel={() => { setDraftCategory(null); setEditingMemory(null) }} onSaved={refresh} />}</></AppShell>
}
